- docs/data-sources/compute_flavors.md
- docs/data-sources/identity_role_v3.md
- docs/data-sources/vpc.md
- docs/data-sources/vpc_route.md
- docs/data-sources/vpc_subnet.md
- docs/data-sources/vpc_subnet_ids.md
- docs/index.md
- docs/resources/compute_eip_associate.md
- docs/resources/compute_instance.md
- docs/resources/compute_interface_attach.md
- docs/resources/compute_volume_attach.md
- docs/resources/dns_recordset.md
- docs/resources/dns_zone.md
- docs/resources/evs_snapshot.md
- docs/resources/evs_volume.md
- docs/resources/identity_group_membership_v3.md
- docs/resources/identity_group_v3.md
- docs/resources/identity_role_assignment_v3.md
- docs/resources/identity_user_v3.md
- docs/resources/networking_secgroup.md
- docs/resources/networking_secgroup_rule.md
- docs/resources/vpc.md
- docs/resources/vpc_eip.md
- docs/resources/vpc_peering.md
- docs/resources/vpc_route.md
- docs/resources/vpc_subnet.md
> fix some doc problems

- docs/resources/fgs_function.md
- g42cloud/provider.go
- g42cloud/resource_g42cloud_fgs_function_test.go
- go.mod
- go.sum
add resource fgs_function
Test results:
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccFgsV2Function'
TF_ACC=1 go test ./g42cloud -v -run TestAccFgsV2Function -timeout 360m -parallel=4
=== RUN   TestAccFgsV2Function_basic
=== PAUSE TestAccFgsV2Function_basic
=== RUN   TestAccFgsV2Function_withEpsId
=== PAUSE TestAccFgsV2Function_withEpsId
=== RUN   TestAccFgsV2Function_text
=== PAUSE TestAccFgsV2Function_text
=== CONT  TestAccFgsV2Function_basic
=== CONT  TestAccFgsV2Function_text
=== CONT  TestAccFgsV2Function_withEpsId
--- PASS: TestAccFgsV2Function_text (14.59s)
--- PASS: TestAccFgsV2Function_withEpsId (14.86s)
--- PASS: TestAccFgsV2Function_basic (26.24s)
PASS
ok …
```
> add resource fgs_function

- go.mod
- go.sum
update reference of huaweicloud
> update reference of huaweicloud

- CHANGELOG.md
> Update CHANGELOG for v1.1.0

- CHANGELOG.md
> Update CHANGELOG for v1.2.0

- docs/index.md
- g42cloud/provider.go
support security_token in g42cloud
> feat(iam): support security_token in g42cloud

- CHANGELOG.md
> Update CHANGELOG for v1.2.1

- CHANGELOG.md
- go.mod
- go.sum
> Update CHANGELOG for v1.3.0

- go.mod
- go.sum
> update reference of g42cloud

- .github/workflows/ci.yml
- .github/workflows/release.yml
update go version for ci and release
> chore: update go version for ci and release

- .gitignore
- g42cloud/provider.go
- g42cloud/resource_g42cloud_evs_volume_test.go
- go.mod
- go.sum
1. update references
2. update gitignore
> refactor(references): update references

- CHANGELOG.md
> Update CHANGELOG for v1.3.1

- docs/resources/ces_alarmrule.md
- docs/resources/compute_instance.md
- g42cloud/provider.go
- g42cloud/resource_g42cloud_dms_instance_v1.go
fixes #56 
fix some problems of docs, logs and default value
> fix(doc): fix some problems of docs, logs and default value

- docs/resources/compute_instance.md
- g42cloud/common.go
- g42cloud/compute_instance_v2_networking.go
- g42cloud/provider.go
- g42cloud/resource_g42cloud_compute_instance.go
- g42cloud/resource_g42cloud_compute_instance_test.go
- g42cloud/resource_g42cloud_rds_instance.go
- g42cloud/resource_schema.go
- go.mod
- go.sum
support disk encryption
Test results:
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccComputeV2Instance_basic'
TF_ACC=1 go test ./g42cloud -v -run TestAccComputeV2Instance_basic -timeout 360m -parallel=4
=== RUN   TestAccComputeV2Instance_basic
=== PAUSE TestAccComputeV2Instance_basic
=== CONT  TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (141.82s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud      141.881s
make testacc TEST='./g42cloud' TESTARGS='-run TestAccComputeV2Instance_disks'
TF_ACC=1 go test ./g42cloud -v -run TestAccComputeV2Instance_disks -timeout 360m -parallel=4
=== RUN …
```
> feat(ecs/instance) support disk encryption

- CHANGELOG.md
> Update CHANGELOG for v1.4.0

- docs/data-sources/bms_flavors.md
- docs/resources/bms_instance.md
- g42cloud/provider.go
- g42cloud/services/acceptance/bms/data_source_huaweicloud_bms_flavors_test.go
- g42cloud/services/acceptance/bms/resource_huaweicloud_bms_instance_test.go
add bms resources
g42cloud_bms_flavors
g42cloud_bms_instance
there is no available bms flavor for now, so no test result
> feat(bms): add bms resources

- docs/resources/mapreduce_cluster.md
- docs/resources/mapreduce_job.md
- g42cloud/provider.go
- g42cloud/services/acceptance/mrs/resource_g42cloud_mapreduce_cluster_test.go
- g42cloud/services/acceptance/mrs/resource_g42cloud_mapreduce_job_test.go
add new resources
g42cloud_mapreduce_cluster
g42cloud_mapreduce_job
there is no available flavor in g42cloud, so no test result
> feat(mrs): add new mrs resources

- docs/resources/obs_bucket.md
- docs/resources/obs_bucket_object.md
- docs/resources/obs_bucket_policy.md
- g42cloud/resource_g42cloud_obs_bucket_object_test.go
feat(obs): update obs docs
fixes #xxx
```release-note
feat(obs): update obs docs
```
```
...
PASS
```
> feat(obs): update obs docs

- CHANGELOG.md
> Update CHANGELOG for v1.5.0

- docs/data-sources/cbr_vaults.md
- docs/data-sources/elb_certificate.md
- docs/resources/elb_certificate.md
- docs/resources/elb_ipgroup.md
- docs/resources/elb_l7policy.md
- docs/resources/elb_l7rule.md
- docs/resources/elb_listener.md
- docs/resources/elb_loadbalancer.md
- docs/resources/elb_member.md
- docs/resources/elb_monitor.md
- docs/resources/elb_pool.md
- docs/resources/smn_subscription.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/cbr/resource_g42cloud_cbr_vault_test.go
- g42cloud/services/acceptance/elb/data_source_huaweicloud_elb_certificate_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_certificate_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_ipgroup_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_l7policy_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_l7rule_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_listener_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_loadbalancer_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_member_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_monitor_test.go
- g42cloud/services/acceptance/elb/resource_huaweicloud_elb_pool_test.go
add new elb resources
fixes #xxx
```release-note
data_source_huaweicloud_elb_certificate
resource_huaweicloud_elb_certificate
resource_huaweicloud_elb_ipgroup
resource_huaweicloud_elb_l7policy
resource_huaweicloud_elb_l7rule
resource_huaweicloud_elb_listener
resource_huaweicloud_elb_loadbalancer
resource_huaweicloud_elb_member
resource_huaweicloud_elb_monitor
resource_huaweicloud_elb_pool
```
```
make testacc TEST='./g42cloud/services/acceptance/elb' TESTARGS='-run TestAccDataSourceELbCertificateV3_basic'
==> …
```
> feat(elb): add new elb resources

- docs/resources/networking_vip.md
- docs/resources/networking_vip_associate.md
- g42cloud/provider.go
- g42cloud/services/acceptance/vpc/resource_g42cloud_networking_vip_associate_test.go
- g42cloud/services/acceptance/vpc/resource_g42cloud_networking_vip_test.go
- go.mod
- go.sum
add new vip resources
fixes #xxx
```release-note
The following resources added:
g42cloud_networking_vip
g42cloud_networking_vip_associate
```
```
make testacc TEST='./g42cloud/services/acceptance/vpc' TESTARGS='-run TestAccNetworkingVip_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/vpc -v -run TestAccNetworkingVip_basic -timeout 360m -parallel=4
=== RUN   TestAccNetworkingVip_basic
=== PAUSE TestAccNetworkingVip_basic
=== CONT  TestAccNetworkingVip_basic
--- PASS: …
```
> feat(vpc/vip): add new vip resources

- docs/resources/obs_bucket.md
- go.mod
- go.sum
fixes #xxx
```release-note
```
```
...
PASS
```
> update reference and doc

- g42cloud/compute_instance_v2_networking.go
Fix the wrong client usage for VPC offline ver.1 sdk. 
fixes #xxx
```release-note
1. fix the wrong client usage.
```
```
NONE
```
> fix(port/query): fix the wrong client usage

- g42cloud/resource_g42cloud_compute_instance.go
use v1 api to update port
fixes #xxx
```release-note
use v1 api to update port
```
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccComputeV2Instance_basic'
TF_ACC=1 go test ./g42cloud -v -run TestAccComputeV2Instance_basic -timeout 360m -parallel=4
=== RUN   TestAccComputeV2Instance_basic
=== PAUSE TestAccComputeV2Instance_basic
=== CONT  TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (151.53s)
PASS
ok …
```
> refactor(ecs): use v1 api to update port

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.6.0

- docs/data-sources/kms_data_key.md
- docs/data-sources/kms_key.md
- docs/resources/cce_node.md
- docs/resources/cce_node_pool.md
- docs/resources/kms_key.md
fixes #xxx
```release-note
1. fix docs of cce node and node pool about root volume encryption
2. move kms resources to dew
```
```
...
PASS
```
> refactor(doc): update docs

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.7.0

- examples/high-available-web/README.md
- examples/high-available-web/main.tf
- examples/high-available-web/variables.tf
- examples/high-available-web/versions.tf
fixes #xxx
```release-note
```
```
...
PASS
```
> Add exmples of high available web

- examples/high-available-web/ecs.tf
- examples/high-available-web/elb.tf
- examples/high-available-web/network.tf
- examples/high-available-web/rds.tf
- examples/high-available-web/variables.tf
fixes #xxx
```release-note
```
```
...
PASS
```
> Add eps support to examples

- docs/resources/smn_subscription.md
- examples/high-available-web/README.md
fixes #xxx
```release-note
```
```
...
PASS
```
> fix(doc): fix some doc lint problems

- docs/resources/dc_virtual_gateway.md
- docs/resources/dc_virtual_interface.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/dc/resource_huaweicloud_dc_virtual_gateway_test.go
- g42cloud/services/acceptance/dc/resource_huaweicloud_dc_virtual_interface_test.go
fixes #xxx
```release-note
```
```
make testacc TEST='./g42cloud/services/acceptance/dc' TESTARGS='-run TestAccVirtualGateway_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/dc -v -run TestAccVirtualGateway_basic -timeout 360m -parallel=4
=== RUN   TestAccVirtualGateway_basic
=== PAUSE TestAccVirtualGateway_basic
=== CONT  TestAccVirtualGateway_basic
--- PASS: TestAccVirtualGateway_basic (54.51s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/service …
```
> feat(dc): add dc resources

- docs/resources/as_configuration.md
- docs/resources/as_group.md
- docs/resources/as_policy.md
fixes #xxx
```release-note
```
```
...
PASS
```
> feat(as): update AS docs

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.8.0

- examples/3tier-webapp/security_group.tf
fixes #xxx
```release-note
```
```
...
PASS
```
> security_group.tf

- examples/3tier-webapp/variables.tf
fixes #xxx
```release-note
```
```
...
PASS
```
> variables.tf

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.8.1

- docs/data-sources/sms_source_servers.md
- docs/resources/sms_server_template.md
- docs/resources/sms_task.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/common/resources.go
- g42cloud/services/acceptance/sms/data_source_g42cloud_sms_source_servers_test.go
- g42cloud/services/acceptance/sms/resource_g42cloud_sms_server_template_test.go
- g42cloud/services/acceptance/sms/resource_g42cloud_sms_task_test.go
fixes #xxx
```release-note
new data_source:
g42cloud_sms_source_servers
new resources:
g42cloud_sms_server_template
g42cloud_sms_task
```
```
make testacc TEST='./g42cloud/services/acceptance/sms' TESTARGS='-run TestAccSourceServers_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/sms -v -run TestAccSourceServers_basic -timeout 360m -parallel=4
=== RUN   TestAccSourceServers_basic
=== PAUSE TestAccSourceServers_basic
=== CONT  TestAccSourceServers_basic
--- PASS: …
```
> feat(sms): add new sms resources

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.9.0

- docs/resources/vpc_route.md
fixes #xxx
```release-note
```
```
...
PASS
```
> doc(vpc): update doc of vpc route

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.9.1

- docs/data-sources/rms_policy_definitions.md
- docs/resources/rms_policy_assignment.md
- docs/resources/rms_resource_aggregation_authorization.md
- docs/resources/rms_resource_aggregator.md
- docs/resources/rms_resource_recorder.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/rms/data_source_g42cloud_rms_policy_definitions_test.go
- g42cloud/services/acceptance/rms/resource_g42cloud_rms_policy_assignment_test.go
- g42cloud/services/acceptance/rms/resource_g42cloud_rms_resource_aggregation_authorization_test.go
- g42cloud/services/acceptance/rms/resource_g42cloud_rms_resource_aggregator_test.go
- g42cloud/services/acceptance/rms/resource_g42cloud_rms_resource_recorder_test.go
fixes #xxx
```release-note
new data_source:
rms_policy_definitions
new resources:
rms_policy_assignment
rms_resource_aggregation_authorization
rms_resource_aggregator
rms_resource_recorder
```
```
make testacc TEST='./g42cloud/services/acceptance/rms' TESTARGS='-run TestAccDataPolicyDefinitions'
TF_ACC=1 go test ./g42cloud/services/acceptance/rms -v -run TestAccDataPolicyDefinitions -timeout 360m -parallel=4
=== RUN   TestAccDataPolicyDefinitions_basic
=== PAUSE …
```
> feat(rms): add rms resources

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.10.0

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.10.1

- CHANGELOG.md
fixes #xxx
```release-note
```
```
...
PASS
```
> Update CHANGELOG for v1.11.0

- docs/resources/csms_secret.md
- g42cloud/provider.go
- g42cloud/services/acceptance/dew/resource_g42cloud_csms_secret_test.go
import `resource_g42cloud_csms_secret` resource, unit test and document
fixes #xxx
```release-note
```
```
=== RUN   TestAccDewCsmsSecret_basic
=== PAUSE TestAccDewCsmsSecret_basic
=== CONT  TestAccDewCsmsSecret_basic
--- PASS: TestAccDewCsmsSecret_basic (50.65s)
PASS
coverage: 11.1% of statements in ../../../../../terraform-provider-g42cloud/...
```
> feat(DEW): import DEW resource, unit test and document.

- docs/guides/remote-state-backend.md
add backend document.
fixes #xxx
```release-note
```
```
```
> docs(backend): add backend document.

- docs/resources/cce_node_pool.md
- g42cloud/resource_g42cloud_cce_node_pool_test.go
add `security_groups` and `pod_security_groups` parameters and unit test
fixes #xxx
```release-note
```
```
=== RUN   TestAccCCENodePool_security_groups
=== PAUSE TestAccCCENodePool_security_groups
=== CONT  TestAccCCENodePool_security_groups
--- PASS: TestAccCCENodePool_security_groups (754.42s)
PASS
```
> feat(CCE): add two parameters

- .github/workflows/prow.yml
- OWNERS
fixes #xxx
```release-note
```
```
NONE
```
> feat(workflow): add Prow GitHub action workflow

- .github/workflows/lgtm-merger.yml
- .github/workflows/prow.yml
fixes #xxx
```release-note
```
```
NONE
```
> workflow: add automatic merge PR action

- .github/workflows/lgtm-merger.yml
fixes #xxx
```release-note
```
```
...
PASS
```
> workflow: fix github-token setter

- scripts/scanner/file.go
- scripts/scanner/main.go
- scripts/scanner/markdown_checker.go
- scripts/scanner/product.go
- scripts/scanner/product_catalog.json
- scripts/scanner/schema.go
- scripts/scanner/schema_block.go
- scripts/scanner/special.go
- export the schema of resources and data sources
- check consistency between schema and markdown
```release-note
```
```
...
PASS
```
> chore(scripts): generate schema and check consistency of markdown

- g42cloud/provider.go
optimize the format of the provider.go
fixes #xxx
```release-note
```
```
...
PASS
```
> style(provider): optimize the format of the provider.go

- .github/workflows/lgtm-merger.yml
- .github/workflows/prow.yml
fixes #xxx
```release-note
```
```
NA
```
> fix: Prow workflows does not run in the forked repository

- OWNERS
fixes #xxx
```release-note
```
```
...
PASS
```
> workflow: add Jason-Zhang9309 to reviewers and approvers

- docs/resources/ces_alarm_template.md
- docs/resources/ces_resource_group.md
- g42cloud/provider.go
- g42cloud/services/acceptance/ces/resource_g42cloud_ces_alarm_template_test.go
- g42cloud/services/acceptance/ces/resource_g42cloud_ces_resource_group_test.go
import CES resource, unit test and document
fixes #xxx
```release-note
```
```markdown
=== RUN   TestAccCesAlarmTemplate_basic
=== PAUSE TestAccCesAlarmTemplate_basic
=== CONT  TestAccCesAlarmTemplate_basic
--- PASS: TestAccCesAlarmTemplate_basic (46.39s)
PASS
coverage: 11.1% of statements in ../../../../../terraform-provider-g42cloud/...
```
```markdown
=== RUN   TestAccResourceGroup_basic
=== PAUSE TestAccResourceGroup_basic
=== CONT  TestAccResourceGroup_basic
--- PASS: TestAccResourceGroup_basic (290.47s)
PASS
coverage: 11.7% of statements in …
```
> feat(CES): import CES resource, unit test and document

- docs/data-sources/cce_addon_template.md
- docs/data-sources/cce_cluster.md
- docs/resources/cce_addon.md
- docs/resources/cce_cluster.md
- docs/resources/cce_node.md
- docs/resources/cce_node_pool.md
fix CCE docs issues and upgrade terraform version imported from huaweicloud
**Attention**: The new added parameters are tested by modify basic function. the function is git rollbacked to recover original state when the parameters are passed. This is why the 'Acceptance Steps Performed' is basic.
fixes #xxx
```release-note
```
```
=== RUN   TestAccCCENodeV3_basic
=== PAUSE TestAccCCENodeV3_basic
=== CONT  TestAccCCENodeV3_basic
--- PASS: TestAccCCENodeV3_basic (311.22s)
PASS
=== RUN   TestAccCCENodePool_basic
=== PAUSE TestAccCCENodePool_basic
=== …
```
> docs(CCE): fix docs issues and upgrade.

- docs/resources/css_configuration.md
- g42cloud/provider.go
- g42cloud/services/acceptance/css/resource_g42cloud_css_cluster_test.go
- g42cloud/services/acceptance/css/resource_g42cloud_css_configuration_test.go
import CSS resource, unit test and document
fixes #xxx
```release-note
```
```markdown
=== RUN   TestAccCssConfiguration_basic
=== PAUSE TestAccCssConfiguration_basic
=== CONT  TestAccCssConfiguration_basic
--- PASS: TestAccCssConfiguration_basic (1002.58s)
PASS
=== RUN   TestAccCssCluster_basic
=== PAUSE TestAccCssCluster_basic
=== CONT  TestAccCssCluster_basic
--- PASS: TestAccCssCluster_basic (1408.08s)
PASS
```
> feat(CSS): import CSS resource, unit test and document

- .github/labeler.yml
- .github/workflows/pr_labeler.yml
fixes #xxx
```release-note
```
```
NONE
```
> workflow: add Pull Request Labeler

- OWNERS
fixes #xxx
```release-note
```
```
```
> chore: update reviewers

- .github/workflows/prow.yml
fixes #xxx
```release-note
```
```
NONE
```
> workflow: update Prow workflow

- .github/workflows/doc-lint.yml
- .github/workflows/pr-size-labeler.yml
- .github/workflows/prow-command.yml
- .github/workflows/prow-merge-on-lgtm.yml
- .gitignore
fixes #xxx
```release-note
```
```
```
> refactor: update .gitignore and workflow names

- .github/workflows/prow-command.yml
- .github/workflows/prow-merge-on-lgtm.yml
fixes #xxx
```release-note
```
```
```
> fix: fix prow jobs running conditions

- docs/data-sources/ddm_engines.md
- docs/data-sources/ddm_flavors.md
- g42cloud/provider.go
- g42cloud/services/acceptance/ddm/data_source_g42cloud_ddm_engines_test.go
- g42cloud/services/acceptance/ddm/data_source_g42cloud_ddm_flavors_test.go
import DDM resource, unit test and document.
fixes #xxx
```release-note
```
```md
=== RUN   TestAccDatasourceDdmEngines_basic
=== PAUSE TestAccDatasourceDdmEngines_basic
=== CONT  TestAccDatasourceDdmEngines_basic
--- PASS: TestAccDatasourceDdmEngines_basic (20.36s)
PASS
coverage: 8.0% of statements in ../../../../../terraform-provider-g42cloud/...
```
```md
=== RUN   TestAccDatasourceDdmFlavors_basic
=== PAUSE TestAccDatasourceDdmFlavors_basic
=== CONT  TestAccDatasourceDdmFlavors_basic
--- PASS: TestAccDatasourceDdmFlavors_basic (23.18s)
PASS …
```
> feat(DDM): import DDM resource, unit test and document.

- docs/data-sources/cbr_backup.md
- g42cloud/provider.go
- g42cloud/services/acceptance/cbr/data_source_g42cloud_cbr_backup_test.go
transfer cbr resource from Huaweicloud provider to G42cloudprovider
import cbr resource and add unit test and docs
```release-note
```
```
=== RUN   TestAccDataBackup_basic
=== PAUSE TestAccDataBackup_basic
=== CONT  TestAccDataBackup_basic
--- PASS: TestAccDataBackup_basic (599.71s)
PASS
```
> feat(cbr): import cbr resource and add unit test and docs

- docs/data-sources/apig_groups.md
- docs/resources/apig_acl_policy.md
- docs/resources/apig_acl_policy_associate.md
- docs/resources/apig_appcode.md
- docs/resources/apig_application_authorization.md
- docs/resources/apig_channel.md
- docs/resources/apig_instance_routes.md
- docs/resources/apig_plugin.md
- docs/resources/apig_plugin_associate.md
- docs/resources/apig_signature.md
- docs/resources/apig_signature_associate.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/apig/data_source_g42cloud_apig_groups_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_acl_policy_associate_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_acl_policy_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_appcode_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_application_authorization_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_channel_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_instance_routes_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_plugin_associate_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_plugin_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_signature_associate_test.go
- g42cloud/services/acceptance/apig/resource_g42cloud_apig_signature_test.go
fixes #xxx
```release-note
```
```
...
PASS
```
> feat(apig): import apig resource and add unit test and docs

- docs/data-sources/elb_loadbalancers.md
- docs/data-sources/elb_pools.md
- docs/resources/elb_logtank.md
- docs/resources/elb_security_policy.md
- g42cloud/provider.go
- g42cloud/services/acceptance/elb/data_source_g42cloud_elb_loadbalancers_test.go
- g42cloud/services/acceptance/elb/data_source_g42cloud_elb_pools_test.go
- g42cloud/services/acceptance/elb/resource_g42cloud_elb_logtank_test.go
- g42cloud/services/acceptance/elb/resource_g42cloud_elb_security_policy_test.go
fixes #xxx
```release-note
```
```
=== RUN   TestAccElbLogTank_basic
=== PAUSE TestAccElbLogTank_basic
=== CONT  TestAccElbLogTank_basic
--- PASS: TestAccElbLogTank_basic (142.01s)
PASS
```
```
=== RUN   TestAccSecurityPoliciesV3_basic
=== PAUSE TestAccSecurityPoliciesV3_basic
=== CONT  TestAccSecurityPoliciesV3_basic
--- PASS: TestAccSecurityPoliciesV3_basic (38.11s)
PASS
coverage: 11.0% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN   TestAccDatasourceLoadBalancers_basic
=== PAUSE …
```
> feat(elb): import elb resource and add unit test and docs

- CHANGELOG.md
fixes #xxx
```release-note
```
```
```
> release: update CHANGELOG for v1.12.0

- docs/resources/cpts_project.md
- g42cloud/provider.go
- g42cloud/services/acceptance/cpts/resource_g42cloud_cpts_project_test.go
transfer cpts resource from HuaweiCloud to G42Cloud
import cpts resource and add unit test and docs
```release-note
```
```
=== RUN   TestAccProject_basic
--- PASS: TestAccProject_basic (39.75s)
PASS
```
> feat(cpts): add CPTS resource support

- docs/data-sources/dns_recordsets.md
- docs/data-sources/dns_zones.md
- g42cloud/provider.go
- g42cloud/services/acceptance/dns/data_source_g42cloud_dns_recordsets_test.go
- g42cloud/services/acceptance/dns/data_source_g42cloud_dns_zones_test.go
transfer dns resource from HuaweiCloud to G42Cloud
import dns resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccDatasourceDNSRecordsets_basic
=== PAUSE TestAccDatasourceDNSRecordsets_basic
=== CONT  TestAccDatasourceDNSRecordsets_basic
--- PASS: TestAccDatasourceDNSRecordsets_basic (60.84s)
PASS
coverage: 8.0% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN   TestAccDatasourceDNSRecordsets_private
=== PAUSE TestAccDatasourceDNSRecordsets_private
=== CONT  TestAccDatasourceDNSRecordsets_private
--- PASS: TestAccDatasourceDNSRecordsets_private (74.80s)
PASS
coverage: 8.0% of statements in …
```
> feat(dns): add DNS data sources

- docs/data-sources/smn_message_templates.md
- docs/data-sources/smn_topics.md
- docs/resources/smn_logtank.md
- docs/resources/smn_message_template.md
- g42cloud/provider.go
- g42cloud/services/acceptance/smn/data_source_g42cloud_smn_message_templates_test.go
- g42cloud/services/acceptance/smn/data_source_g42cloud_smn_topics_test.go
- g42cloud/services/acceptance/smn/resource_g42cloud_smn_logtank_test.go
- g42cloud/services/acceptance/smn/resource_g42cloud_smn_message_template_test.go
import smn resource, unit tests and docs
import smn resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccDatasourceSmnMessageTemplates_basic
=== PAUSE TestAccDatasourceSmnMessageTemplates_basic
=== CONT  TestAccDatasourceSmnMessageTemplates_basic
--- PASS: TestAccDatasourceSmnMessageTemplates_basic (30.48s)
PASS
coverage: 8.2% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN   TestAccDataTopics_basic
=== PAUSE TestAccDataTopics_basic
=== CONT  TestAccDataTopics_basic
--- PASS: TestAccDataTopics_basic (40.29s)
PASS
coverage: 8.2% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN …
```
> feat(smn): add SMN resources and data sources support

- docs/resources/identity_provider.md
- docs/resources/identity_provider_conversion.md
- g42cloud/provider.go
- g42cloud/services/acceptance/iam/resource_g42cloud_identity_provider_conversion_test.go
- g42cloud/services/acceptance/iam/resource_g42cloud_identity_provider_test.go
import IAM resource, unit test and document.
fixes #xxx
```release-note
```
```md
=== RUN   TestAccIdentityProvider_basic
=== PAUSE TestAccIdentityProvider_basic
=== CONT  TestAccIdentityProvider_basic
--- PASS: TestAccIdentityProvider_basic (50.68s)
PASS
coverage: 11.1% of statements in ../../../../../terraform-provider-g42cloud/...
```
```md
=== RUN   TestAccIdentityProviderConversion_basic
=== PAUSE TestAccIdentityProviderConversion_basic
=== CONT  TestAccIdentityProviderConversion_basic
--- PASS: TestAccIdentityProviderConversion_basic …
```
> feat(IAM): import IAM resource, unit test and document.

- docs/resources/swr_image_retention_policy.md
- g42cloud/provider.go
- g42cloud/services/acceptance/swr/resource_g42cloud_swr_image_retention_policy_test.go
fixes #xxx
```release-note
```
```md
=== RUN   TestAccSwrImageRetentionPolicy_basic
=== PAUSE TestAccSwrImageRetentionPolicy_basic
=== CONT  TestAccSwrImageRetentionPolicy_basic
--- PASS: TestAccSwrImageRetentionPolicy_basic (48.50s)
PASS
=== RUN   TestAccSwrImageRetentionPolicy_tag_rule
=== PAUSE TestAccSwrImageRetentionPolicy_tag_rule
=== CONT  TestAccSwrImageRetentionPolicy_tag_rule
--- PASS: TestAccSwrImageRetentionPolicy_tag_rule (47.30s)
PASS
coverage: 11.2% of …
```
> feat(SWR): import SWR resource, unit test and document

- docs/data-sources/mapreduce_clusters.md
- g42cloud/provider.go
- g42cloud/services/acceptance/mrs/data_source_g42cloud_mapreduce_clusters_test.go
fixes #xxx
```release-note
```
```
=== RUN   TestAccDatasourceMrsClusters_basic
=== PAUSE TestAccDatasourceMrsClusters_basic
=== CONT  TestAccDatasourceMrsClusters_basic
--- PASS: TestAccDatasourceMrsClusters_basic (1124.49s)
PASS
```
> feat(MRS): import MRS dataSource of clusters.

- docs/data-sources/cbr_backup.md
- g42cloud/provider.go
- g42cloud/services/acceptance/cbr/data_source_g42cloud_cbr_backup_test.go
import IAM resource and document.
fixes #xxx
```release-note
```
```
=== RUN   TestAccDataBackup_basic
=== PAUSE TestAccDataBackup_basic
=== CONT  TestAccDataBackup_basic
--- PASS: TestAccDataBackup_basic (576.90s)
PASS
coverage: 8.7% of statements in ../../../../../terraform-provider-g42cloud/...
```
> feat(cbr): import cbr resource, unit tests and docs

- docs/resources/images_image_copy.md
- docs/resources/images_image_share.md
- docs/resources/images_image_share_accepter.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/ims/resource_g42cloud_images_image_copy_test.go
- g42cloud/services/acceptance/ims/resource_g42cloud_images_image_share_accepter_test.go
- g42cloud/services/acceptance/ims/resource_g42cloud_images_image_share_test.go
import IMS resource, unit test and document.
fixes #xxx
```release-note
```
```md
=== RUN   TestAccImsImageShareAccepter_basic
=== PAUSE TestAccImsImageShareAccepter_basic
=== CONT  TestAccImsImageShareAccepter_basic
--- PASS: TestAccImsImageShareAccepter_basic (27.59s)
PASS
coverage: 11.0% of statements in ../../../../../terraform-provider-g42cloud/...
```
```md
=== RUN   TestAccImsImageShare_basic
=== PAUSE TestAccImsImageShare_basic
=== CONT  TestAccImsImageShare_basic
--- PASS: TestAccImsImageShare_basic (480.82s)
PASS
coverage: 11.4% of …
```
> feat(IMS): import IMS resource, unit test and document.

- docs/resources/nat_private_dnat_rule.md
- docs/resources/nat_private_gateway.md
- docs/resources/nat_private_snat_rule.md
- docs/resources/nat_private_transit_ip.md
- g42cloud/provider.go
- g42cloud/services/acceptance/nat/resource_g42cloud_nat_private_dnat_rule_test.go
- g42cloud/services/acceptance/nat/resource_g42cloud_nat_private_gateway_test.go
- g42cloud/services/acceptance/nat/resource_g42cloud_nat_private_snat_rule_test.go
- g42cloud/services/acceptance/nat/resource_g42cloud_nat_private_transit_ip_test.go
fixes #xxx
```release-note
```
```
...
PASS
```
> feat(nat): import nat resource and add unit test and docs

- docs/resources/ges_metadata.md
- g42cloud/provider.go
- g42cloud/services/acceptance/ges/resource_g42cloud_ges_metadata_test.go
transfer ges resource from HuaweiCloud to G42Cloud
import ges resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccGesMetadata_basic
=== PAUSE TestAccGesMetadata_basic
=== CONT  TestAccGesMetadata_basic
--- PASS: TestAccGesMetadata_basic (93.30s)
PASS
coverage: 11.4% of statements in ../../../../../terraform-provider-g42cloud/...
```
> feat(ges): import ges_metadata resource and doc

- CHANGELOG.md
fixes #xxx
```release-note
```
```
```
> Update CHANGELOG for v1.13.0

- docs/resources/rds_instance.md
- g42cloud/resource_g42cloud_rds_instance.go
fixes #xxx
```release-note
```
```
=== RUN   TestAccRdsInstanceV3_basic
=== PAUSE TestAccRdsInstanceV3_basic
=== CONT  TestAccRdsInstanceV3_basic
--- PASS: TestAccRdsInstanceV3_basic (1230.03s)
PASS
```
> feat(RDS): add DSS support for RDS instance

- docs/resources/cce_cluster.md
fixes #xxx
```release-note
```
```
...
PASS
```
> docs(CCE): modify extend_params to extend_param
