- docs/resources/as_configuration.md
- docs/resources/as_group.md
- docs/resources/as_policy.md
- g42cloud/resource_g42cloud_as_configuration_v1_test.go
- g42cloud/resource_g42cloud_as_group_v1_test.go
- g42cloud/resource_g42cloud_as_policy_v1_test.go
- go.mod
- go.sum
- vendor/github.com/huaweicloud/golangsdk/openstack/iec/v1/subnets/requests.go
- vendor/github.com/huaweicloud/golangsdk/openstack/iec/v1/subnets/results.go
- vendor/github.com/huaweicloud/golangsdk/openstack/iec/v1/subnets/urls.go
- vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/provider.go
- vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_as_configuration_v1.go
- vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_iec_vpc_subnet.go
- vendor/github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/resource_huaweicloud_obs_bucket.go
- vendor/modules.txt
The following resources were added:
resource_g42cloud_as_configuration
resource_g42cloud_as_group
resource_g42cloud_as_policy
```bash
make testacc TEST='./g42cloud' TESTARGS='-run TestAccAS'
TF_ACC=1 go test ./g42cloud -v -run TestAccAS -timeout 360m -parallel=4
=== RUN   TestAccASV1Configuration_basic
=== PAUSE TestAccASV1Configuration_basic
=== RUN   TestAccASV1Group_basic
=== PAUSE TestAccASV1Group_basic
=== RUN   TestAccASV1Policy_basic
=== PAUSE TestAccASV1Policy_basic
=== CONT  TestAccASV1Configuration_basic
=== CONT  TestAccASV1Policy_basic
=== CONT  TestAccASV1Group_basic
--- PASS: TestAccASV1Configuration_basic (128.94s)
--- PASS: TestAccASV1Policy_basic (163.41s)
--- PASS: TestAccASV1Group_basic (247.13s)
PASS
ok …
```
> add AS resources

- .gitignore
add vendor directory in gitignore
the vendor directory can be used in local development and debugging, but will not be uploaded
> add vendor directory in gitignore

- docs/resources/smn_subscription.md
- docs/resources/smn_topic.md
- g42cloud/provider.go
- g42cloud/resource_g42cloud_smn_subscription_v2_test.go
- g42cloud/resource_g42cloud_smn_topic_v2_test.go
- go.mod
- go.sum
resource_g42cloud_smn_subscription
resource_g42cloud_smn_topic
Test results:
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccSMNV2Topic'
TF_ACC=1 go test ./g42cloud -v -run TestAccSMNV2Topic -timeout 360m -parallel=4
=== RUN   TestAccSMNV2Topic_basic
=== PAUSE TestAccSMNV2Topic_basic
=== CONT  TestAccSMNV2Topic_basic
--- PASS: TestAccSMNV2Topic_basic (15.74s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud      15.783s
make testacc TEST='./g42cloud' TESTARGS='-run TestAccSMNV2Subscription'
TF_ACC=1 go test ./g42cloud -v -run TestAccSMNV2Subscription -timeout 360m -parallel=4
=== RUN …
```
> add smn resources

- docs/data-sources/obs_bucket_object.md
- docs/resources/obs_bucket.md
- docs/resources/obs_bucket_object.md
- docs/resources/obs_bucket_policy.md
- g42cloud/data_source_g42cloud_obs_bucket_object_test.go
- g42cloud/provider_test.go
- g42cloud/resource_g42cloud_obs_bucket_object_test.go
- g42cloud/resource_g42cloud_obs_bucket_policy_test.go
- g42cloud/resource_g42cloud_obs_bucket_test.go
- go.mod
- go.sum
data_source_g42cloud_obs_bucket_object
resource_g42cloud_obs_bucket_object
resource_g42cloud_obs_bucket_policy
resource_g42cloud_obs_bucket
Test results:
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccG42CloudObsBucketObjectDataSource'
TF_ACC=1 go test ./g42cloud -v -run TestAccG42CloudObsBucketObjectDataSource -timeout 360m -parallel=4
=== RUN   TestAccG42CloudObsBucketObjectDataSource_content
=== PAUSE TestAccG42CloudObsBucketObjectDataSource_content
=== RUN   TestAccG42CloudObsBucketObjectDataSource_source
=== PAUSE TestAccG42CloudObsBucketObjectDataSource_source
=== RUN   TestAccG42CloudObsBucketObjectDataSource_allParams
=== PAUSE TestAccG42CloudObsBucketObjectDataSource_allParams …
```
> add resources of OBS

- docs/resources/dli_queue.md
- g42cloud/provider.go
- g42cloud/resource_g42cloud_dli_queue_v1_test.go
- g42cloud/transport.go
add resource dli_queue in g42cloud
Test result:
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccDliQueueV1_basic'
TF_ACC=1 go test ./g42cloud -v -run TestAccDliQueueV1_basic -timeout 360m -parallel=4
=== RUN   TestAccDliQueueV1_basic
=== PAUSE TestAccDliQueueV1_basic
=== CONT  TestAccDliQueueV1_basic
--- PASS: TestAccDliQueueV1_basic (19.48s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud      19.522s
```
> feat(dli): add resource dli_queue in g42cloud

- docs/resources/ces_alarmrule.md
- g42cloud/provider.go
- g42cloud/resource_g42cloud_ces_alarmrule_test.go
add resource ces_alarmrule in g42cloud
test result:
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccCESAlarmRule_basic'
TF_ACC=1 go test ./g42cloud -v -run TestAccCESAlarmRule_basic -timeout 360m -parallel=4
=== RUN   TestAccCESAlarmRule_basic
=== PAUSE TestAccCESAlarmRule_basic
=== CONT  TestAccCESAlarmRule_basic
--- PASS: TestAccCESAlarmRule_basic (156.50s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud      156.554s
```
> feat(ces): add resource ces_alarmrule in g42cloud

- docs/data-sources/vpc_route_table.md
- docs/resources/vpc_route_table.md
- g42cloud/provider.go
- g42cloud/services/acceptance/vpc/data_source_g42cloud_vpc_route_table_test.go
- g42cloud/services/acceptance/vpc/resource_g42cloud_vpc_route_table_test.go
add route table resource and data_source
```
make testacc TEST='./g42cloud/services/acceptance/vpc' TESTARGS='-run TestAccVpcRouteTable_basic'==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./g42cloud/services/acceptance/vpc -v -run TestAccVpcRouteTable_basic -timeout 360m -parallel=4
=== RUN   TestAccVpcRouteTable_basic
=== PAUSE TestAccVpcRouteTable_basic
=== CONT  TestAccVpcRouteTable_basic
--- PASS: TestAccVpcRouteTable_basic (103.32s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/services/acceptance/vpc      103.422s
make testacc TEST='./g42cloud/services/acceptance/vpc' TESTARGS='-run TestAccVpcRouteTable_multiRoutes' 
TF_ACC=1 go test …
```
> feat(vpc/route_table): add route table resource and data_source

- docs/resources/dns_ptrrecord.md
- g42cloud/provider.go
- g42cloud/provider_test.go
- g42cloud/resource_g42cloud_dns_ptrrecord_v2_test.go
add dns_ptrrecord resource in g42cloud
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccDNSV2PtrRecord_basic'
TF_ACC=1 go test ./g42cloud -v -run TestAccDNSV2PtrRecord_basic -timeout 360m -parallel=4
=== RUN   TestAccDNSV2PtrRecord_basic
=== PAUSE TestAccDNSV2PtrRecord_basic
=== CONT  TestAccDNSV2PtrRecord_basic
--- PASS: TestAccDNSV2PtrRecord_basic (64.40s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud      64.447s
make testacc TEST='./g42cloud' TESTARGS='-run TestAccDNSV2PtrRecord_withEpsId'
TF_ACC=1 go test ./g42cloud -v -run TestAccDNSV2PtrRecord_withEpsId -timeout 360m -parallel=4
=== RUN   TestAccDNSV2PtrRecord_withEpsId
=== …
```
> feat(dns/pptrrecord): add dns_ptrrecord resource in g42cloud

- docs/data-sources/enterprise_project.md
- docs/resources/enterprise_project.md
- g42cloud/provider.go
- g42cloud/services/acceptance/eps/data_source_g42cloud_enterprise_project_test.go
- g42cloud/services/acceptance/eps/resource_g42cloud_enterprise_project_test.go
add EPS resources in G42 cloud
**Test results**:
```
make testacc TEST='./g42cloud/services/acceptance/eps' TESTARGS='-run TestAccEnterpriseProjectDataSource_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/eps -v -run TestAccEnterpriseProjectDataSource_basic -timeout 360m -parallel=4
=== RUN   TestAccEnterpriseProjectDataSource_basic
=== PAUSE TestAccEnterpriseProjectDataSource_basic
=== CONT  TestAccEnterpriseProjectDataSource_basic
--- PASS: TestAccEnterpriseProjectDataSource_basic (16.16s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/services/acceptance/eps      16.215s
make testacc TEST='./g42cloud/services/acceptance/eps' TESTARGS='-run TestAccEnterpriseProject_basic'
==> Checking …
```
> feat(eps): add EPS resources in G42 cloud

- docs/resources/swr_organization.md
- docs/resources/swr_organization_permissions.md
- docs/resources/swr_repository.md
- docs/resources/swr_repository_sharing.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/swr/resource_g42cloud_swr_organization_permissions_test.go
- g42cloud/services/acceptance/swr/resource_g42cloud_swr_organization_test.go
- g42cloud/services/acceptance/swr/resource_g42cloud_swr_repository_sharing_test.go
- g42cloud/services/acceptance/swr/resource_g42cloud_swr_repository_test.go
add swr resources in G42 cloud
g42cloud_swr_organization_permissions
g42cloud_swr_organization
g42cloud_swr_repository_sharing
g42cloud_swr_repository
**Test results:**:
```
make testacc TEST='./g42cloud/services/acceptance/swr' TESTARGS='-run TestAccSwrOrganizationPermissions_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/swr -v -run TestAccSwrOrganizationPermissions_basic -timeout 360m -parallel=4
=== RUN   TestAccSwrOrganizationPermissions_basic
=== PAUSE TestAccSwrOrganizationPermissions_basic
=== CONT  TestAccSwrOrganizationPermissions_basic
--- PASS: TestAccSwrOrganizationPermissions_basic (35.65s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/servic …
```
> feat(swr): add swr resources in G42 cloud

- docs/data-sources/cbr_vaults.md
- docs/resources/cbr_policy.md
- docs/resources/cbr_vault.md
- g42cloud/provider.go
- g42cloud/services/acceptance/cbr/data_source_g42cloud_cbr_vaults_test.go
- g42cloud/services/acceptance/cbr/resource_g42cloud_cbr_policy_test.go
- g42cloud/services/acceptance/cbr/resource_g42cloud_cbr_vault_test.go
- go.mod
- go.sum
The following resource are added:
**data_sources**:
g42cloud_cbr_vaults
**resources**:
g42cloud_cbr_policy
g42cloud_cbr_vault
**Test results**:
```
make testacc TEST='./g42cloud/services/acceptance/cbr' TESTARGS='-run TestAcc'
TF_ACC=1 go test ./g42cloud/services/acceptance/cbr -v -run TestAcc -timeout 360m -parallel=4
=== RUN   TestAccCbrVaultsV3_BasicServer
=== PAUSE TestAccCbrVaultsV3_BasicServer
=== RUN   TestAccCbrVaultsV3_BasicVolume
=== PAUSE TestAccCbrVaultsV3_BasicVolume
=== RUN   TestAccCbrVaultsV3_BasicTurbo
=== PAUSE TestAccCbrVaultsV3_BasicTurbo
=== RUN   TestAccCBRV3Policy_basic
=== PAUSE TestAccCBRV3Policy_basic
=== RUN   TestAccCBRV3Policy_retention
=== PAUSE TestAccCBRV3Policy_retention
=== RUN …
```
> feat(cbr): add cbr resources in G42 cloud

- docs/resources/tms_tags.md
- g42cloud/provider.go
- g42cloud/services/acceptance/tms/resource_huaweicloud_tms_tags_test.go
- go.mod
- go.sum
The following resource are added:
**resources**:
g42cloud_tms_tags
**Test results**:
```
make testacc TEST='./g42cloud/services/acceptance/tms' TESTARGS='-run TestAccTmsTag_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/tms -v -run TestAccTmsTag_basic -timeout 360m -parallel=4
=== RUN   TestAccTmsTag_basic
--- PASS: TestAccTmsTag_basic (17.82s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/services/acceptance/tms      17.879s
```
> feat(tms): add tms_tags resource in g42cloud

- docs/resources/cts_data_tracker.md
- docs/resources/cts_tracker.md
- g42cloud/provider.go
- g42cloud/services/acceptance/cts/resource_g42cloud_cts_data_tracker_test.go
- g42cloud/services/acceptance/cts/resource_g42cloud_cts_tracker_test.go
add resources:
g42cloud_cts_data_tracker
g42cloud_cts_tracker
Test result:
```
make testacc TEST='./g42cloud/services/acceptance/cts' TESTARGS='-run TestAcc'
TF_ACC=1 go test ./g42cloud/services/acceptance/cts -v -run TestAcc -timeout 360m -parallel=4
=== RUN   TestAccCTSDataTracker_basic
=== PAUSE TestAccCTSDataTracker_basic
=== RUN   TestAccCTSTracker_basic
=== PAUSE TestAccCTSTracker_basic
=== CONT  TestAccCTSDataTracker_basic
=== CONT  TestAccCTSTracker_basic
--- PASS: TestAccCTSTracker_basic (49.45s)
--- PASS: TestAccCTSDataTracker_basic (51.79s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/services/acceptance/cts      51.881s
```
> feat(cts): add new cts resources

- docs/resources/lts_group.md
- docs/resources/lts_stream.md
- g42cloud/provider.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_group_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_stream_test.go
add resources:
g42cloud_lts_group
g42cloud_lts_stream
Test results:
```
make testacc TEST='./g42cloud/services/acceptance/lts' TESTARGS='-run TestAcc'
TF_ACC=1 go test ./g42cloud/services/acceptance/lts -v -run TestAcc -timeout 360m -parallel=4
=== RUN   TestAccLogTankGroupV2_basic
=== PAUSE TestAccLogTankGroupV2_basic
=== RUN   TestAccLogTankStreamV2_basic
=== PAUSE TestAccLogTankStreamV2_basic
=== CONT  TestAccLogTankGroupV2_basic
=== CONT  TestAccLogTankStreamV2_basic
--- PASS: TestAccLogTankStreamV2_basic (16.35s)
--- PASS: TestAccLogTankGroupV2_basic (31.12s)
PASS
ok      github.com/g42cloud-terraform/terraform-provider-g42cloud/g42cloud/services/acceptance/lts      31.192s
```
> feat(lts): add new lts resources

- g42cloud/provider.go
- g42cloud/resource_g42cloud_compute_eip_associate_test.go
- g42cloud/resource_g42cloud_compute_instance_test.go
- g42cloud/resource_g42cloud_compute_servergroup.go
- g42cloud/resource_g42cloud_compute_servergroup_test.go
use v2 api as the GET func of v1 dose not exist
fixes #xxx
```release-note
use v2 api as the GET func of v1 dose not exist
```
```
make testacc TEST='./g42cloud' TESTARGS='-run TestAccComputeServerGroup_basic'
TF_ACC=1 go test ./g42cloud -v -run TestAccComputeServerGroup_basic -timeout 360m -parallel=4
=== RUN   TestAccComputeServerGroup_basic
=== PAUSE TestAccComputeServerGroup_basic
=== CONT  TestAccComputeServerGroup_basic
--- PASS: TestAccComputeServerGroup_basic (19.05s)
PASS
ok …
```
> fix(server_group): use v2 api as the GET func of v1 dose not exist

- g42cloud/resource_g42cloud_compute_instance.go
- go.mod
- go.sum
use v1 api to reset the password
fixes #xxx
```release-note
use v1 api to reset the password
```
```
...
PASS
```
> feat(ecs): use v1 api to reset the password

- docs/data-sources/waf_certificate.md
- docs/data-sources/waf_dedicated_instances.md
- docs/data-sources/waf_policies.md
- docs/data-sources/waf_reference_tables.md
- docs/resources/rds_instance.md
- docs/resources/waf_certificate.md
- docs/resources/waf_dedicated_domain.md
- docs/resources/waf_dedicated_instance.md
- docs/resources/waf_domain.md
- docs/resources/waf_policy.md
- docs/resources/waf_reference_table.md
- docs/resources/waf_rule_blacklist.md
- docs/resources/waf_rule_data_masking.md
- docs/resources/waf_rule_web_tamper_protection.md
- g42cloud/provider.go
- g42cloud/services/acceptance/waf/data_source_g42cloud_waf_certificate_test.go
- g42cloud/services/acceptance/waf/data_source_g42cloud_waf_dedicated_instances_test.go
- g42cloud/services/acceptance/waf/data_source_g42cloud_waf_policies_test.go
- g42cloud/services/acceptance/waf/data_source_g42cloud_waf_reference_table_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_certificate_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_dedicated_domain_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_dedicated_instance_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_domain_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_policy_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_reference_table_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_rule_blacklist_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_rule_data_masking_test.go
- g42cloud/services/acceptance/waf/resource_g42cloud_waf_rule_web_tamper_protection_test.go
- go.mod
- go.sum
fixes #xxx
```release-note
1. new data_sources:
waf_certificate
waf_dedicated_instances
waf_policies
waf_reference_tables
2. new resources
waf_certificate
waf_dedicated_domain
waf_dedicated_instance
waf_domain
waf_policy
waf_reference_table
waf_rule_blacklist
waf_rule_data_masking
waf_rule_web_tamper_protection
```
```
make testacc TEST='./g42cloud/services/acceptance/waf' TESTARGS='-run TestAccWafDedicatedInstance_basic'
TF_ACC=1 go test ./g42cloud/services/acceptance/waf -v -run …
```
> feat(waf): add waf resources

- docs/data-sources/as_configurations.md
- docs/data-sources/as_groups.md
- docs/resources/as_bandwidth_policy.md
- docs/resources/as_instance_attach.md
- docs/resources/as_lifecycle_hook.md
- docs/resources/as_notification.md
- g42cloud/provider.go
- g42cloud/services/acceptance/as/data_source_g42cloud_as_configurations_test.go
- g42cloud/services/acceptance/as/data_source_g42cloud_as_groups_test.go
- g42cloud/services/acceptance/as/resource_g42cloud_as_bandwidth_policy_test.go
- g42cloud/services/acceptance/as/resource_g42cloud_as_instance_attach_test.go
- g42cloud/services/acceptance/as/resource_g42cloud_as_lifecycle_hook_test.go
- g42cloud/services/acceptance/as/resource_g42cloud_as_notification_test.go
import AS resource, unit test and document
fixes #xxx
```release-note
```
```markdown
=== RUN   TestAccASBandWidthPolicy_basic
=== PAUSE TestAccASBandWidthPolicy_basic
=== CONT  TestAccASBandWidthPolicy_basic
--- PASS: TestAccASBandWidthPolicy_basic (89.62s)
PASS
=== RUN   TestAccASBandWidthPolicy_alarm
=== PAUSE TestAccASBandWidthPolicy_alarm
=== CONT  TestAccASBandWidthPolicy_alarm
--- PASS: TestAccASBandWidthPolicy_alarm (49.02s)
PASS
coverage: 11.2% of statements …
```
> feat(AS): import AS resource, unit test and document

- docs/data-sources/cce_clusters.md
- docs/data-sources/cce_nodes.md
- docs/resources/cce_namespace.md
- docs/resources/cce_pvc.md
- g42cloud/provider.go
- g42cloud/services/acceptance/cce/data_source_g42cloud_cce_clusters_test.go
- g42cloud/services/acceptance/cce/data_source_g42cloud_cce_nodes_test.go
- g42cloud/services/acceptance/cce/resource_g42cloud_cce_namespace_test.go
- g42cloud/services/acceptance/cce/resource_g42cloud_cce_pvc_test.go
import CCE resource, unit test and document
fixes #xxx
```release-note
```
```markdown
=== RUN   TestAccCCENamespaceV1_basic
=== PAUSE TestAccCCENamespaceV1_basic
=== CONT  TestAccCCENamespaceV1_basic
--- PASS: TestAccCCENamespaceV1_basic (566.04s)
PASS
coverage: 14.1% of statements in ../../../../../terraform-provider-g42cloud/...
```
```markdown
=== RUN   TestAccCcePersistentVolumeClaimsV1_basic
=== PAUSE TestAccCcePersistentVolumeClaimsV1_basic
=== CONT  TestAccCcePersistentVolumeClaimsV1_basic
--- PASS: …
```
> feat(CCE): import CCE resource, unit test and document

- docs/data-sources/csms_secret_version.md
- g42cloud/provider.go
- g42cloud/services/acceptance/dew/data_source_g42cloud_csms_secret_version_test.go
import DEW resource, unit test and document.
fixes #xxx
```release-note
```
```md
=== RUN   TestAccDewCsmsSecretVersion_basic
=== PAUSE TestAccDewCsmsSecretVersion_basic
=== CONT  TestAccDewCsmsSecretVersion_basic
--- PASS: TestAccDewCsmsSecretVersion_basic (48.92s)
PASS
coverage: 8.2% of statements in ../../../../../terraform-provider-g42cloud/...
```
> feat(DEW): add a DataSource to query the CSMS secret

- docs/data-sources/rds_backups.md
- docs/data-sources/rds_engine_versions.md
- docs/data-sources/rds_instances.md
- docs/data-sources/rds_sqlserver_collations.md
- docs/data-sources/rds_storage_types.md
- docs/resources/rds_backup.md
- docs/resources/rds_mysql_account.md
- docs/resources/rds_mysql_database.md
- docs/resources/rds_mysql_database_privilege.md
- docs/resources/rds_sql_audit.md
- g42cloud/provider.go
- g42cloud/services/acceptance/rds/data_source_g42cloud_rds_backups_test.go
- g42cloud/services/acceptance/rds/data_source_g42cloud_rds_engine_versions_test.go
- g42cloud/services/acceptance/rds/data_source_g42cloud_rds_instances_test.go
- g42cloud/services/acceptance/rds/data_source_g42cloud_rds_sqlserver_collations_test.go
- g42cloud/services/acceptance/rds/data_source_g42cloud_rds_storage_types_test.go
- g42cloud/services/acceptance/rds/resource_g42cloud_rds_backup_test.go
- g42cloud/services/acceptance/rds/resource_g42cloud_rds_mysql_account_test.go
- g42cloud/services/acceptance/rds/resource_g42cloud_rds_mysql_database_privilege_test.go
- g42cloud/services/acceptance/rds/resource_g42cloud_rds_mysql_database_test.go
- g42cloud/services/acceptance/rds/resource_g42cloud_rds_sql_audit_test.go
import RDS resource and dataSource, and its unit test and document
fixes #xxx
```release-note
```
‍‍‍‍‍‍‍
```md
=== RUN   TestAccBackup_mysql_basic
=== PAUSE TestAccBackup_mysql_basic
=== CONT  TestAccBackup_mysql_basic
--- PASS: TestAccBackup_mysql_basic (1266.59s)
PASS
coverage: 29.7% of statements in ../../../../../terraform-provider-g42cloud/...
=== RUN   TestAccBackup_sqlserver_basic
=== PAUSE TestAccBackup_sqlserver_basic
=== CONT  TestAccBackup_sqlserver_basic
--- PASS: TestAccBackup_sqlserver_basic (2294.28s)
PASS
coverage: 29.7% of …
```
> feat(RDS): import RDS resource and dataSource, and its unit test and document

- docs/data-sources/dds_instances.md
- docs/resources/dds_audit_log_policy.md
- docs/resources/dds_backup.md
- docs/resources/dds_database_role.md
- docs/resources/dds_database_user.md
- docs/resources/dds_parameter_template.md
- g42cloud/provider.go
- g42cloud/services/acceptance/dds/data_source_g42cloud_dds_instances_test.go
- g42cloud/services/acceptance/dds/resource_g42cloud_dds_audit_log_policy_test.go
- g42cloud/services/acceptance/dds/resource_g42cloud_dds_backup_test.go
- g42cloud/services/acceptance/dds/resource_g42cloud_dds_database_role_test.go
- g42cloud/services/acceptance/dds/resource_g42cloud_dds_database_user_test.go
- g42cloud/services/acceptance/dds/resource_g42cloud_dds_parameter_template_test.go
import CSS resource, unit test and document
fixes #xxx
```release-note
```
```markdown
=== RUN   TestAccDatasourceDdsInstance_basic
=== PAUSE TestAccDatasourceDdsInstance_basic
=== CONT  TestAccDatasourceDdsInstance_basic
--- PASS: TestAccDatasourceDdsInstance_basic (888.87s)
PASS
coverage: 8.6% of statements in ../../../../../terraform-provider-g42cloud/...
=== RUN   TestAccDdsBackup_basic
=== PAUSE TestAccDdsBackup_basic
=== CONT  TestAccDdsBackup_basic
--- PASS: TestAccDdsBackup_basic (1186.65s)
PASS
coverage: 14.7% of statements in …
```
> feat(DDS): import DDS resource, unit test and document

- docs/resources/mpc_transcoding_template.md
- docs/resources/mpc_transcoding_template_group.md
- g42cloud/provider.go
- g42cloud/services/acceptance/mpc/resource_g42cloud_mpc_transcoding_template_group_test.go
- g42cloud/services/acceptance/mpc/resource_g42cloud_mpc_transcoding_template_test.go
import MPC resource, unit test and document
fixes #xxx
```release-note
```
```
=== RUN   TestAccTranscodingTemplate_basic
=== PAUSE TestAccTranscodingTemplate_basic
=== CONT  TestAccTranscodingTemplate_basic
--- PASS: TestAccTranscodingTemplate_basic (43.98s)
PASS
coverage: 11.1% of statements in ../../../../../terraform-provider-g42cloud/...
=== RUN   TestAccTranscodingTemplate_basic2
=== PAUSE TestAccTranscodingTemplate_basic2
=== CONT  TestAccTranscodingTemplate_basic2
--- PASS: TestAccTranscodingTemplate_basic2 (23.58s)
PASS
coverage: 11.1% …
```
> feat(MPC): add DataSources to retrieve templates and template groups

- docs/data-sources/dcs_instances.md
- docs/data-sources/dcs_template_detail.md
- docs/data-sources/dcs_templates.md
- docs/resources/dcs_backup.md
- docs/resources/dcs_custom_template.md
- g42cloud/provider.go
- g42cloud/services/acceptance/dcs/data_source_g42cloud_dcs_instances_test.go
- g42cloud/services/acceptance/dcs/data_source_g42cloud_dcs_template_detail_test.go
- g42cloud/services/acceptance/dcs/data_source_huaweicloud_dcs_templates_test.go
- g42cloud/services/acceptance/dcs/resource_g42cloud_dcs_backup_test.go
- g42cloud/services/acceptance/dcs/resource_g42cloud_dcs_custom_template_test.go
- g42cloud/services/acceptance/dcs/resource_g42cloud_dcs_instance_test.go
fixes #xxx
```release-note
```
```
...
PASS
```
> feat(dcs): import dcs resource and add unit test and docs

- README.md
- docs/data-sources/vpc_eip.md
- docs/data-sources/vpc_eips.md
- docs/resources/vpc_bandwidth_associate.md
- g42cloud/provider.go
- g42cloud/services/acceptance/eip/data_source_g42cloud_vpc_eip_test.go
- g42cloud/services/acceptance/eip/data_source_g42cloud_vpc_eips_test.go
- g42cloud/services/acceptance/eip/resource_g42cloud_vpc_bandwidth_associate_test.go
transfer eip resource from HuaweiCloud to G42Cloud
import eip resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccBandWidthAssociate_migrate
=== PAUSE TestAccBandWidthAssociate_migrate
=== CONT  TestAccBandWidthAssociate_migrate
--- PASS: TestAccBandWidthAssociate_migrate (91.76s)
PASS
```
```
=== RUN   TestAccBandWidthAssociate_basic
=== PAUSE TestAccBandWidthAssociate_basic
=== CONT  TestAccBandWidthAssociate_basic
--- PASS: TestAccBandWidthAssociate_basic (70.29s)
PASS
```
> feat(EIP): add EIP resource and data sources

- docs/data-sources/lb_certificate.md
- docs/data-sources/lb_loadbalancer.md
- docs/data-sources/lb_pools.md
- g42cloud/provider.go
- g42cloud/services/acceptance/lb/data_source_g42cloud_lb_certificate_test.go
- g42cloud/services/acceptance/lb/data_source_g42cloud_lb_loadbalancer_test.go
- g42cloud/services/acceptance/lb/data_source_g42cloud_lb_pools_test.go
transfer lb resource from HuaweiCloud to G42Cloud
import lb resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccDataSourceLBCertificateV2_basic
--- PASS: TestAccDataSourceLBCertificateV2_basic (23.40s)
PASS
coverage: 8.0% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN   TestAccELBV2LoadbalancerDataSource_basic
=== PAUSE TestAccELBV2LoadbalancerDataSource_basic
=== CONT  TestAccELBV2LoadbalancerDataSource_basic
--- PASS: TestAccELBV2LoadbalancerDataSource_basic (62.27s)
PASS
coverage: 10.4% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN   TestAccDataLBPools_basic
=== PAUSE …
```
> feat(lb): add LB data sources

- docs/data-sources/networking_secgroups.md
- docs/data-sources/vpc_peering_connection.md
- docs/data-sources/vpc_subnets.md
- docs/data-sources/vpcs.md
- docs/resources/vpc_flow_log.md
- g42cloud/provider.go
- g42cloud/services/acceptance/vpc/data_source_g42cloud_networking_secgroups_test.go
- g42cloud/services/acceptance/vpc/data_source_g42cloud_vpc_peering_connection_test.go
- g42cloud/services/acceptance/vpc/data_source_g42cloud_vpc_subnets_test.go
- g42cloud/services/acceptance/vpc/data_source_g42cloud_vpcs_test.go
- g42cloud/services/acceptance/vpc/resource_g42cloud_vpc_flow_log_test.go
transfer vpc resources from HuaweiCloud to G42Cloud
import vpc resource and add unit test and docs
```release-note
```
```
=== RUN   TestAccFlowLog_basic
=== PAUSE TestAccFlowLog_basic
=== CONT  TestAccFlowLog_basic
--- PASS: TestAccFlowLog_basic (92.37s)
PASS
```
```
=== RUN   TestAccNetworkingSecGroupsDataSource_description
=== PAUSE TestAccNetworkingSecGroupsDataSource_description
=== CONT  TestAccNetworkingSecGroupsDataSource_description
--- PASS: TestAccNetworkingSecGroupsDataSource_description (34.65s)
PASS
coverage: 8.2% of statements in …
```
> feat(vpc): import vpc resource and add unit test and docs

- docs/data-sources/tms_resource_types.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/tms/resource_g42cloud_tms_resource_tags_test.go
transfer tms data sources from HuaweiCloud Provider to G42Cloud Provider
import tms resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccDataSourceResourceTypes_basic
=== PAUSE TestAccDataSourceResourceTypes_basic
=== CONT  TestAccDataSourceResourceTypes_basic
--- PASS: TestAccDataSourceResourceTypes_basic (22.19s)
PASS
coverage: 8.0% of statements in ../../../../../terraform-provider-g42cloud/...
```
```
=== RUN   TestAccDataSourceResourceTypes_filterByRegion
=== PAUSE TestAccDataSourceResourceTypes_filterByRegion
=== CONT  TestAccDataSourceResourceTypes_filterByRegion
--- PASS: TestAccDataSourceResourceTypes_filterByRegion (19.89s)
PASS …
```
> feat(TMS): add a data source to query supported resource types information

- docs/resources/obs_bucket_acl.md
- docs/resources/obs_bucket_object_acl.md
- g42cloud/provider.go
- g42cloud/services/acceptance/obs/resource_g42cloud_obs_bucket_acl_test.go
- g42cloud/services/acceptance/obs/resource_g42cloud_obs_bucket_object_acl_test.go
transfer obs resource from HuaweiCloud Provider to G42Cloud Provider
import obs resource, unit tests and docs
```release-note
```
```
=== RUN   TestAccOBSBucketAcl_basic
=== PAUSE TestAccOBSBucketAcl_basic
=== CONT  TestAccOBSBucketAcl_basic
--- PASS: TestAccOBSBucketAcl_basic (81.70s)
PASS
```
```
=== RUN   TestAccOBSBucketObjectAcl_basic
=== PAUSE TestAccOBSBucketObjectAcl_basic
=== CONT  TestAccOBSBucketObjectAcl_basic
--- PASS: TestAccOBSBucketObjectAcl_basic (82.19s)
PASS
```
```
=== RUN …
```
> feat(obs): add obs resources support

- docs/data-sources/dws_flavors.md
- docs/resources/dws_alarm_subscription.md
- docs/resources/dws_event_subscription.md
- g42cloud/provider.go
- g42cloud/services/acceptance/dws/data_source_g42cloud_dws_flavors_test.go
- g42cloud/services/acceptance/dws/resource_g42cloud_dws_alarm_subscription_test.go
- g42cloud/services/acceptance/dws/resource_g42cloud_dws_event_subscription_test.go
import DWS resource, unit test and document
fixes #xxx
```release-note
```
```md
=== RUN   TestAccDwsAlarmSubs_basic
=== PAUSE TestAccDwsAlarmSubs_basic
=== CONT  TestAccDwsAlarmSubs_basic
--- PASS: TestAccDwsAlarmSubs_basic (106.04s)
PASS
```
```md
=== RUN   TestAccDwsEventSubs_basic
=== PAUSE TestAccDwsEventSubs_basic
=== CONT  TestAccDwsEventSubs_basic
--- PASS: TestAccDwsEventSubs_basic (69.95s)
PASS
coverage: 11.2% of statements in …
```
> feat(DWS): add DWS DataSource and Resources

- docs/data-sources/lts_structuring_custom_templates.md
- docs/resources/lts_aom_access.md
- docs/resources/lts_host_access.md
- docs/resources/lts_host_group.md
- docs/resources/lts_keywords_alarm_rule.md
- docs/resources/lts_search_criteria.md
- docs/resources/lts_sql_alarm_rule.md
- docs/resources/lts_structuring_configuration.md
- docs/resources/lts_structuring_custom_configuration.md
- docs/resources/lts_waf_access.md
- g42cloud/provider.go
- g42cloud/services/acceptance/acceptance.go
- g42cloud/services/acceptance/lts/data_source_g42cloud_lts_structuring_custom_templates_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_aom_access_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_host_access_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_host_group_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_keywords_alarm_rule_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_search_criteria_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_sql_alarm_rule_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_structuring_configuration_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_structuring_custom_configuration_test.go
- g42cloud/services/acceptance/lts/resource_g42cloud_lts_waf_access_test.go
import LTS resource, unit test and document
this PR has modified `acceptance.go`. it will confilict with others.
fixes #xxx
```release-note
```
```md
=== RUN   TestAccAOMAccess_allWorkloads
=== PAUSE TestAccAOMAccess_allWorkloads
=== CONT  TestAccAOMAccess_allWorkloads
--- PASS: TestAccAOMAccess_allWorkloads (53.99s)
PASS
coverage: 11.4% of statements in ../../../../../terraform-provider-g42cloud/...
=== RUN   TestAccAOMAccess_specifyWorkloads
=== PAUSE TestAccAOMAccess_specifyWorkloads
=== CONT  TestAccAOMAccess_specifyWorkloads
--- PASS: …
```
> feat(LTS): import LTS resource, unit test and document
